version: "3"

services:
  postgres:
    image: "postgres:10.4-alpine"
    volumes:
      - "postgres:/var/lib/postgresql/data"
    environment:
      POSTGRES_DB: botw

  redis:
    image: "redis:4.0-alpine"
    command: redis-server
    volumes:
      - "redis:/data"

  app:
    depends_on:
      - "postgres"
      - "redis"
    image: roonglit/botw
    command: ["bundle", "exec", "puma", "-C", "config/puma.rb"]
    ports:
      - "3000:3000"
    environment:
      - RAILS_SERVE_STATIC_FILES=true
      - HOST=http://localhost:3000
      - DATABASE_URL=postgres://postgres@postgres:5432/botw
      - REDIS_URL=redis://redis:6379

volumes:
  redis:
  postgres:
