name: build
on: push
jobs:
  deploy:
    if: github.ref == 'refs/heads/master'
    name: Deploy to production
    runs-on: ubuntu-latest
    env:
      IMAGE: roonglit/botw

    steps:
      - name: Check out repository code
        uses: actions/checkout@master

      - name: Build image
        run: docker build -t ${IMAGE}:${GITHUB_RUN_NUMBER} .
